language: node_js
node_js:
  - node

script:
  - yarn test || true # TODO
  - yarn lint
  - yarn build

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: rtk.intertub.es
  on: master
