language: node_js
node_js:
  - node

script:
  - yarn test
  - yarn build
  - yarn build-index
  - rm dist/index.js dist/index.js.map

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: rtk.intertub.es
  on: master
