language: node_js
node_js:
  - node

script:
  - yarn test
  - yarn lint
  - yarn build
  - yarn build-index
  - mv tmp/index.html dist/index.html

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: rtk.intertub.es
  on: master
