%.utf8: %
	iconv --from-code EUC-JP --to-code UTF-8 $^ > $@

.PHONY: main
main: data/kradfile.json data/radkfile.json

data/.made:
	mkdir -p data && touch $@

data/kradfile.json: kradzip/kradfile.utf8 ./lib/krad.rb | data/.made
	ruby ./lib/krad.rb $@ $<

data/radkfile.json: kradzip/radkfile.utf8 ./lib/radk.rb | data/.made
	ruby ./lib/radk.rb $@ $<
